package com.ohma.thutothebe.dto;

import com.ohma.thutothebe.entity.CurriculumAnalytics;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Map;

public record CurriculumAnalyticsDTO(
    Long id,
    
    @NotNull(message = "Curriculum ID is required")
    Long curriculumId,
    String curriculumTitle,
    
    Long schoolId,
    String schoolName,
    
    Long regionId,
    String regionName,
    
    @NotNull(message = "Report date is required")
    LocalDate reportDate,
    
    @NotNull(message = "Analytics type is required")
    CurriculumAnalytics.AnalyticsType analyticsType,
    
    @NotNull(message = "Aggregation level is required")
    CurriculumAnalytics.AggregationLevel aggregationLevel,
    
    // Implementation Progress Metrics
    Integer totalSchools,
    Integer schoolsStarted,
    Integer schoolsCompleted,
    Double overallProgressPercentage,
    
    // Teacher Metrics
    Integer totalTeachers,
    Integer teachersTrained,
    Integer teachersImplementing,
    Double teacherReadinessScore,
    
    // Student Metrics
    Integer totalStudents,
    Integer studentsEnrolled,
    Double studentPerformanceAverage,
    Double completionRate,
    
    // Resource Metrics
    Integer resourcesAvailable,
    Integer resourcesUtilized,
    Double resourceUtilizationRate,
    
    // Assessment Metrics
    Integer assessmentsConducted,
    Double averageAssessmentScore,
    Double assessmentCompletionRate,
    
    // Time Metrics
    Integer plannedDurationWeeks,
    Integer actualDurationWeeks,
    Double timeEfficiencyRatio,
    
    // Quality Metrics
    Double qualityScore,
    Double alignmentScore,
    Double effectivenessRating,
    
    // Challenges and Issues
    Integer challengesIdentified,
    Integer issuesResolved,
    String riskLevel,
    
    // Additional Data
    Map<String, Object> detailedMetrics,
    Map<String, Object> trendData,
    Map<String, Object> comparativeData,
    
    // Metadata
    @NotNull(message = "Generated by ID is required")
    Long generatedById,
    String generatedByName,
    
    LocalDateTime generatedAt,
    String dataSource,
    String calculationMethod,
    boolean isActive
) {
    public CurriculumAnalyticsDTO {
        if (overallProgressPercentage != null && (overallProgressPercentage < 0 || overallProgressPercentage > 100)) {
            throw new IllegalArgumentException("Overall progress percentage must be between 0 and 100");
        }
        if (completionRate != null && (completionRate < 0 || completionRate > 100)) {
            throw new IllegalArgumentException("Completion rate must be between 0 and 100");
        }
        if (resourceUtilizationRate != null && (resourceUtilizationRate < 0 || resourceUtilizationRate > 100)) {
            throw new IllegalArgumentException("Resource utilization rate must be between 0 and 100");
        }
    }
} 