package com.ohma.thutothebe.dto;

import com.ohma.thutothebe.entity.GradeReportType;
import com.ohma.thutothebe.entity.Term;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;

public record GradeReportDTO(
    Long id,
    
    @NotNull(message = "Student ID is required")
    Long studentId,
    
    Long courseId,
    
    Long classId,
    
    @NotNull(message = "Report type is required")
    GradeReportType reportType,
    
    @NotNull(message = "Term is required")
    Term term,
    
    @NotNull(message = "Academic year is required")
    Integer academicYear,
    
    Double overallGrade,
    
    Double overallPercentage,
    
    String gradeLetter,
    
    Integer rankInClass,
    
    Integer totalStudentsInClass,
    
    String comments,
    
    @NotNull(message = "Generated by user ID is required")
    Long generatedById,
    
    LocalDateTime generatedAt,
    
    String filePath,
    
    boolean active,
    
    LocalDateTime createdAt,
    
    LocalDateTime modifiedAt
) {
    public GradeReportDTO {
        if (studentId == null) {
            throw new IllegalArgumentException("Student ID cannot be null");
        }
        if (reportType == null) {
            throw new IllegalArgumentException("Report type cannot be null");
        }
        if (term == null) {
            throw new IllegalArgumentException("Term cannot be null");
        }
        if (academicYear == null) {
            throw new IllegalArgumentException("Academic year cannot be null");
        }
        if (generatedById == null) {
            throw new IllegalArgumentException("Generated by user ID cannot be null");
        }
        if (academicYear < 2000 || academicYear > 2100) {
            throw new IllegalArgumentException("Academic year must be between 2000 and 2100");
        }
        if (overallGrade != null && (overallGrade < 0 || overallGrade > 100)) {
            throw new IllegalArgumentException("Overall grade must be between 0 and 100");
        }
        if (overallPercentage != null && (overallPercentage < 0 || overallPercentage > 100)) {
            throw new IllegalArgumentException("Overall percentage must be between 0 and 100");
        }
        if (rankInClass != null && rankInClass <= 0) {
            throw new IllegalArgumentException("Rank in class must be positive");
        }
        if (totalStudentsInClass != null && totalStudentsInClass <= 0) {
            throw new IllegalArgumentException("Total students in class must be positive");
        }
    }
} 