package com.ohma.thutothebe.service.impl;

import com.ohma.thutothebe.dto.GradeReportDTO;
import com.ohma.thutothebe.entity.*;
import com.ohma.thutothebe.exception.ResourceNotFoundException;
import com.ohma.thutothebe.mapper.GradeReportMapper;
import com.ohma.thutothebe.repository.*;
import com.ohma.thutothebe.service.GradeReportService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Slf4j
@Service
@Transactional
public class GradeReportServiceImpl extends BaseServiceImpl<GradeReport, GradeReportDTO, Long> 
        implements GradeReportService {

    @Autowired
    private GradeReportRepository reportRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private CourseRepository courseRepository;

    @Autowired
    private ClassRepository classRepository;

    @Autowired
    private GradeRepository gradeRepository;

    @Autowired
    private GradeReportMapper reportMapper;

    public GradeReportServiceImpl(GradeReportRepository reportRepository) {
        super(reportRepository);
        this.reportRepository = reportRepository;
    }

    @Override
    protected GradeReport mapToEntity(GradeReportDTO dto) {
        return reportMapper.toEntity(dto);
    }

    @Override
    protected GradeReportDTO mapToDto(GradeReport entity) {
        return reportMapper.toDto(entity);
    }

    @Override
    protected void updateEntity(GradeReport entity, GradeReportDTO dto) {
        entity.setReportType(dto.reportType());
        entity.setTerm(dto.term());
        entity.setAcademicYear(dto.academicYear());
        entity.setOverallGrade(dto.overallGrade());
        entity.setOverallPercentage(dto.overallPercentage());
        entity.setGradeLetter(dto.gradeLetter());
        entity.setRankInClass(dto.rankInClass());
        entity.setTotalStudentsInClass(dto.totalStudentsInClass());
        entity.setComments(dto.comments());
        entity.setFilePath(dto.filePath());
        entity.setActive(dto.active());
        entity.setModifiedAt(LocalDateTime.now());
    }

    @Override
    public GradeReportDTO create(GradeReportDTO dto) {
        User student = userRepository.findById(dto.studentId())
                .orElseThrow(() -> new ResourceNotFoundException("Student not found with id: " + dto.studentId()));
        
        User generatedBy = userRepository.findById(dto.generatedById())
                .orElseThrow(() -> new ResourceNotFoundException("Generated by user not found with id: " + dto.generatedById()));

        Course course = null;
        if (dto.courseId() != null) {
            course = courseRepository.findById(dto.courseId())
                    .orElseThrow(() -> new ResourceNotFoundException("Course not found with id: " + dto.courseId()));
        }

        com.ohma.thutothebe.entity.Class classEntity = null;
        if (dto.classId() != null) {
            classEntity = classRepository.findById(dto.classId())
                    .orElseThrow(() -> new ResourceNotFoundException("Class not found with id: " + dto.classId()));
        }

        GradeReport report = reportMapper.toEntityWithReferences(dto, student, course, classEntity, generatedBy);
        beforeCreate(report);
        GradeReport savedReport = reportRepository.save(report);
        
        log.info("Created grade report with id: {} for student: {}", savedReport.getId(), student.getId());
        return reportMapper.toDto(savedReport);
    }

    @Override
    public List<GradeReportDTO> findByGeneratedByIdOrderByGeneratedAtDesc(Long userId) {
        return reportRepository.findByGeneratedByIdOrderByGeneratedAtDesc(userId)
                .stream()
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<GradeReportDTO> findByCourseIdOrderByGeneratedAtDesc(Long courseId) {
        return reportRepository.findByCourseIdOrderByGeneratedAtDesc(courseId)
                .stream()
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<GradeReportDTO> findByTermOrderByGeneratedAtDesc(Term term) {
        return reportRepository.findByTermOrderByGeneratedAtDesc(term)
                .stream()
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<GradeReportDTO> findByReportTypeOrderByGeneratedAtDesc(GradeReportType reportType) {
        return reportRepository.findByReportTypeOrderByGeneratedAtDesc(reportType)
                .stream()
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<GradeReportDTO> findByCourseIdAndTermOrderByGeneratedAtDesc(Long courseId, Term term) {
        return reportRepository.findByCourseIdAndTermOrderByGeneratedAtDesc(courseId, term)
                .stream()
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<GradeReportDTO> findByCourseIdAndTermAndReportTypeOrderByGeneratedAtDesc(
            Long courseId, Term term, GradeReportType reportType) {
        return reportRepository.findByCourseIdAndTermAndReportTypeOrderByGeneratedAtDesc(courseId, term, reportType)
                .stream()
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<GradeReportDTO> findByGeneratedAtBetweenOrderByGeneratedAtDesc(
            LocalDateTime startDate, LocalDateTime endDate) {
        return reportRepository.findByGeneratedAtBetweenOrderByGeneratedAtDesc(startDate, endDate)
                .stream()
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<GradeReportDTO> findByGeneratedByIdAndCourseIdOrderByGeneratedAtDesc(
            Long userId, Long courseId) {
        return reportRepository.findByGeneratedByIdAndCourseIdOrderByGeneratedAtDesc(userId, courseId)
                .stream()
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public Long countByGeneratedByIdAndGeneratedAtAfter(Long userId, LocalDateTime startDate) {
        return reportRepository.countByGeneratedByIdAndGeneratedAtAfter(userId, startDate);
    }

    @Override
    public Optional<GradeReportDTO> findByFileName(String fileName) {
        return reportRepository.findByFileName(fileName)
                .map(reportMapper::toDto);
    }

    @Override
    public GradeReportDTO generateStudentIndividualReport(Long studentId, Long courseId, Term term, 
                                                         Integer academicYear, Long generatedById) {
        // Calculate student's performance in the specific course
        List<Grade> grades = gradeRepository.findByStudentIdAndCourseIdAndActive(studentId, courseId, true);
        
        Double overallGrade = calculateOverallGrade(grades);
        Double overallPercentage = (overallGrade / 100.0) * 100;
        String gradeLetter = calculateGradeLetter(overallGrade);
        
        GradeReportDTO reportDTO = new GradeReportDTO(
                null, studentId, courseId, null, GradeReportType.STUDENT_INDIVIDUAL,
                term, academicYear, overallGrade, overallPercentage, gradeLetter,
                null, null, "Individual student performance report", generatedById,
                LocalDateTime.now(), null, true, null, null
        );
        
        return create(reportDTO);
    }

    @Override
    public GradeReportDTO generateStudentTermReport(Long studentId, Term term, Integer academicYear, Long generatedById) {
        // Calculate student's performance across all courses for the term
        List<Grade> grades = gradeRepository.findByStudentIdAndTermAndActive(studentId, term, true);
        
        Double overallGrade = calculateOverallGrade(grades);
        Double overallPercentage = (overallGrade / 100.0) * 100;
        String gradeLetter = calculateGradeLetter(overallGrade);
        
        GradeReportDTO reportDTO = new GradeReportDTO(
                null, studentId, null, null, GradeReportType.STUDENT_TERM,
                term, academicYear, overallGrade, overallPercentage, gradeLetter,
                null, null, "Student term performance report", generatedById,
                LocalDateTime.now(), null, true, null, null
        );
        
        return create(reportDTO);
    }

    @Override
    public GradeReportDTO generateStudentAnnualReport(Long studentId, Integer academicYear, Long generatedById) {
        // Calculate student's performance for the entire academic year
        List<Grade> grades = gradeRepository.findByStudentIdAndAcademicYearAndActive(studentId, academicYear, true);
        
        Double overallGrade = calculateOverallGrade(grades);
        Double overallPercentage = (overallGrade / 100.0) * 100;
        String gradeLetter = calculateGradeLetter(overallGrade);
        
        GradeReportDTO reportDTO = new GradeReportDTO(
                null, studentId, null, null, GradeReportType.STUDENT_ANNUAL,
                null, academicYear, overallGrade, overallPercentage, gradeLetter,
                null, null, "Student annual performance report", generatedById,
                LocalDateTime.now(), null, true, null, null
        );
        
        return create(reportDTO);
    }

    @Override
    public GradeReportDTO generateClassSummaryReport(Long classId, Term term, Integer academicYear, Long generatedById) {
        // Generate summary report for entire class
        List<Grade> classGrades = gradeRepository.findByClassIdAndActive(classId, true);
        
        Double averageGrade = classGrades.stream()
                .mapToDouble(Grade::getScore)
                .average()
                .orElse(0.0);
        
        GradeReportDTO reportDTO = new GradeReportDTO(
                null, null, null, classId, GradeReportType.CLASS_SUMMARY,
                term, academicYear, averageGrade, (averageGrade / 100.0) * 100, 
                calculateGradeLetter(averageGrade), null, classGrades.size(),
                "Class performance summary report", generatedById,
                LocalDateTime.now(), null, true, null, null
        );
        
        return create(reportDTO);
    }

    @Override
    public GradeReportDTO generateSubjectSummaryReport(Long courseId, Term term, Integer academicYear, Long generatedById) {
        // Generate summary report for specific subject/course
        List<Grade> courseGrades = gradeRepository.findByCourseIdAndActive(courseId, true);
        
        Double averageGrade = courseGrades.stream()
                .mapToDouble(Grade::getScore)
                .average()
                .orElse(0.0);
        
        GradeReportDTO reportDTO = new GradeReportDTO(
                null, null, courseId, null, GradeReportType.SUBJECT_SUMMARY,
                term, academicYear, averageGrade, (averageGrade / 100.0) * 100,
                calculateGradeLetter(averageGrade), null, courseGrades.size(),
                "Subject performance summary report", generatedById,
                LocalDateTime.now(), null, true, null, null
        );
        
        return create(reportDTO);
    }

    @Override
    public GradeReportDTO generateCourseSummaryReport(Long courseId, Term term, Integer academicYear, Long generatedById) {
        return generateSubjectSummaryReport(courseId, term, academicYear, generatedById);
    }

    @Override
    public GradeReportDTO generateProgressReport(Long studentId, Term term, Integer academicYear, Long generatedById) {
        // Generate progress report showing improvement over time
        List<Grade> currentTermGrades = gradeRepository.findByStudentIdAndTermAndActive(studentId, term, true);
        
        Double currentAverage = calculateOverallGrade(currentTermGrades);
        
        GradeReportDTO reportDTO = new GradeReportDTO(
                null, studentId, null, null, GradeReportType.PROGRESS_REPORT,
                term, academicYear, currentAverage, (currentAverage / 100.0) * 100,
                calculateGradeLetter(currentAverage), null, null,
                "Student progress tracking report", generatedById,
                LocalDateTime.now(), null, true, null, null
        );
        
        return create(reportDTO);
    }

    @Override
    public GradeReportDTO generateTranscript(Long studentId, Integer academicYear, Long generatedById) {
        // Generate official academic transcript
        List<Grade> allGrades = gradeRepository.findByStudentIdAndAcademicYearAndActive(studentId, academicYear, true);
        
        Double cumulativeGPA = calculateOverallGrade(allGrades);
        
        GradeReportDTO reportDTO = new GradeReportDTO(
                null, studentId, null, null, GradeReportType.TRANSCRIPT,
                null, academicYear, cumulativeGPA, (cumulativeGPA / 100.0) * 100,
                calculateGradeLetter(cumulativeGPA), null, null,
                "Official academic transcript", generatedById,
                LocalDateTime.now(), null, true, null, null
        );
        
        return create(reportDTO);
    }

    @Override
    public byte[] exportReportToPdf(Long reportId) {
        // Implementation would use PDF generation library like iText or Apache PDFBox
        log.info("Exporting report {} to PDF", reportId);
        // Placeholder implementation
        return new byte[0];
    }

    @Override
    public byte[] exportReportToExcel(Long reportId) {
        // Implementation would use Apache POI for Excel generation
        log.info("Exporting report {} to Excel", reportId);
        // Placeholder implementation
        return new byte[0];
    }

    @Override
    public String saveReportFile(Long reportId, byte[] fileContent, String fileExtension) {
        // Implementation would save file to configured storage location
        String fileName = "report_" + reportId + "_" + System.currentTimeMillis() + "." + fileExtension;
        log.info("Saving report file: {}", fileName);
        
        // Update report with file path
        GradeReport report = reportRepository.findById(reportId)
                .orElseThrow(() -> new ResourceNotFoundException("Report not found with id: " + reportId));
        report.setFilePath("/reports/" + fileName);
        reportRepository.save(report);
        
        return fileName;
    }

    @Override
    public void deleteReportFile(Long reportId) {
        GradeReport report = reportRepository.findById(reportId)
                .orElseThrow(() -> new ResourceNotFoundException("Report not found with id: " + reportId));
        
        if (report.getFilePath() != null) {
            // Implementation would delete physical file
            log.info("Deleting report file: {}", report.getFilePath());
            report.setFilePath(null);
            reportRepository.save(report);
        }
    }

    @Override
    public List<GradeReportDTO> findRecentReports(int limit) {
        return reportRepository.findAll()
                .stream()
                .sorted((r1, r2) -> r2.getGeneratedAt().compareTo(r1.getGeneratedAt()))
                .limit(limit)
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public List<GradeReportDTO> findReportsByStudent(Long studentId) {
        return reportRepository.findAll()
                .stream()
                .filter(report -> report.getStudent() != null && report.getStudent().getId().equals(studentId))
                .map(reportMapper::toDto)
                .collect(Collectors.toList());
    }

    private Double calculateOverallGrade(List<Grade> grades) {
        if (grades.isEmpty()) {
            return 0.0;
        }
        
        return grades.stream()
                .mapToDouble(grade -> grade.getScore() * (grade.getWeight() != null ? grade.getWeight() : 1.0))
                .average()
                .orElse(0.0);
    }

    private String calculateGradeLetter(Double score) {
        if (score >= 80) return "A";
        if (score >= 70) return "B";
        if (score >= 60) return "C";
        if (score >= 50) return "D";
        return "F";
    }
} 