package com.ohma.thutothebe.entity;

public enum UserRole {
    SUPER_ADMIN,
    MINISTRY_EXECUTIVE,
    MINISTRY_STAFF,
    DATA_PROTECTION_OFFICER,
    DIRECTOR,
    REGIONAL_ADMIN,
    REGIONAL_OFFICER,
    SCHOOL_ADMIN,
    SCHOOL_HEAD,
    DEPARTMENT_HEAD,
    SENIOR_TEACHER,
    TEACHER,
    STUDENT,
    PARENT
} 