package com.ohma.thutothebe.entity;

public enum UserActivityType {
    LOGIN,
    LOGOUT,
    PAGE_VIEW,
    ASSIGNMENT_SUBMISSION,
    ASSIGNMENT_GRADING,
    ATTENDANCE_MARKING,
    QUIZ_SUBMISSION,
    FORUM_POST,
    DOCUMENT_UPLOAD,
    DOCUMENT_DOWNLOAD,
    ANNOUNCEMENT_CREATE,
    ANNOUNCEMENT_VIEW,
    CURRICULUM_ACCESS,
    GRADE_ENTRY,
    MESSAGE_SEND,
    CALENDAR_EVENT_CREATE,
    SCHEDULE_VIEW,
    PROFILE_UPDATE,
    SYSTEM_ADMIN_ACTION,
    ERROR_OCCURRED
} 