export const MODAL_BODY_TYPES = {
  // User Management Modals
  USER_ADD_NEW: "USER_ADD_NEW",
  USER_EDIT: "USER_EDIT",
  USER_DELETE_CONFIRMATION: "USER_DELETE_CONFIRMATION",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",
  
  // School Management Modals
  SCHOOL_ADD_NEW: "SCHOOL_ADD_NEW",
  SCHOOL_EDIT: "SCHOOL_EDIT",
  SCHOOL_DELETE_CONFIRMATION: "SCHOOL_DELETE_CONFIRMATION",
  SCHOOL_ASSIGN_ADMIN: "SCHOOL_ASSIGN_ADMIN",
  
  // Region Management Modals
  REGION_ADD_NEW: "REGION_ADD_NEW",
  REGION_EDIT: "REGION_EDIT",
  REGION_DELETE_CONFIRMATION: "REGION_DELETE_CONFIRMATION",
  
  // Role Management Modals
  ROLE_ADD_NEW: "ROLE_ADD_NEW",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE_CONFIRMATION: "ROLE_DELETE_CONFIRMATION",
  ROLE_ASSIGN_PERMISSIONS: "ROLE_ASSIGN_PERMISSIONS",
  
  // Course Management Modals
  COURSE_ADD_NEW: "COURSE_ADD_NEW",
  COURSE_EDIT: "COURSE_EDIT",
  COURSE_DELETE_CONFIRMATION: "COURSE_DELETE_CONFIRMATION",
  COURSE_ASSIGN_TEACHER: "COURSE_ASSIGN_TEACHER",
  
  // System Management Modals
  SYSTEM_RULE_ADD_NEW: "SYSTEM_RULE_ADD_NEW",
  SYSTEM_RULE_EDIT: "SYSTEM_RULE_EDIT",
  SYSTEM_RULE_DELETE_CONFIRMATION: "SYSTEM_RULE_DELETE_CONFIRMATION",
  
  // General Confirmation Modal
  CONFIRMATION: "CONFIRMATION",
  
  // Default Empty Modal
  DEFAULT: "DEFAULT"
};

export const RIGHT_DRAWER_TYPES = {
  // Admin Related Right Drawers
  AUDIT_LOGS: "AUDIT_LOGS",
  SYSTEM_NOTIFICATIONS: "SYSTEM_NOTIFICATIONS",
  USER_ACTIVITY: "USER_ACTIVITY",
  SYSTEM_HEALTH: "SYSTEM_HEALTH",
  NATIONAL_REPORTS: "NATIONAL_REPORTS",
  
  // Monitoring Related Right Drawers
  SYSTEM_MONITORING: "SYSTEM_MONITORING",
  USAGE_ANALYTICS: "USAGE_ANALYTICS",
  PERFORMANCE_METRICS: "PERFORMANCE_METRICS",
  REGIONAL_MONITORING: "REGIONAL_MONITORING",
  SCHOOL_MONITORING: "SCHOOL_MONITORING",
  
  // General Right Drawers
  NOTIFICATIONS: "NOTIFICATIONS",
  SETTINGS: "SETTINGS",
  HELP: "HELP"
}; 