export const MODAL_BODY_TYPES = {
  // User Management Modals
  USER_ADD_NEW: "USER_ADD_NEW",
  USER_EDIT: "USER_EDIT",
  USER_DELETE_CONFIRMATION: "USER_DELETE_CONFIRMATION",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",
  
  // School Management Modals
  SCHOOL_ADD_NEW: "SCHOOL_ADD_NEW",
  SCHOOL_EDIT: "SCHOOL_EDIT",
  SCHOOL_DELETE_CONFIRMATION: "SCHOOL_DELETE_CONFIRMATION",
  SCHOOL_ASSIGN_ADMIN: "SCHOOL_ASSIGN_ADMIN",
  
  // Region Management Modals
  REGION_ADD_NEW: "REGION_ADD_NEW",
  REGION_EDIT: "REGION_EDIT",
  REGION_DELETE_CONFIRMATION: "REGION_DELETE_CONFIRMATION",
  
  // Role Management Modals
  ROLE_ADD_NEW: "ROLE_ADD_NEW",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE_CONFIRMATION: "ROLE_DELETE_CONFIRMATION",
  ROLE_ASSIGN_PERMISSIONS: "ROLE_ASSIGN_PERMISSIONS",
  
  // Course Management Modals
  COURSE_ADD_NEW: "COURSE_ADD_NEW",
  COURSE_EDIT: "COURSE_EDIT",
  COURSE_DELETE_CONFIRMATION: "COURSE_DELETE_CONFIRMATION",
  COURSE_ASSIGN_TEACHER: "COURSE_ASSIGN_TEACHER",
  COURSE_VIEW: "COURSE_VIEW",
  
  // Subject Management Modals
  SUBJECT_ADD_NEW: "SUBJECT_ADD_NEW",
  SUBJECT_EDIT: "SUBJECT_EDIT",
  SUBJECT_DELETE_CONFIRMATION: "SUBJECT_DELETE_CONFIRMATION",
  SUBJECT_ASSIGN_TEACHER: "SUBJECT_ASSIGN_TEACHER",
  
  // Class Management Modals
  CLASS_ADD_NEW: "CLASS_ADD_NEW",
  CLASS_EDIT: "CLASS_EDIT",
  CLASS_DELETE_CONFIRMATION: "CLASS_DELETE_CONFIRMATION",
  CLASS_VIEW: "CLASS_VIEW",
  CLASS_ASSIGN_STUDENT: "CLASS_ASSIGN_STUDENT",
  ATTENDANCE_TAKE: "ATTENDANCE_TAKE",
  REPORT_GENERATE: "REPORT_GENERATE",
  CALENDAR_VIEW: "CALENDAR_VIEW",
  
  // Schedule Management Modals
  SCHEDULE_ADD_NEW: "SCHEDULE_ADD_NEW",
  SCHEDULE_EDIT: "SCHEDULE_EDIT",
  SCHEDULE_DELETE_CONFIRMATION: "SCHEDULE_DELETE_CONFIRMATION",
  SCHEDULE_VIEW: "SCHEDULE_VIEW",
  
  // Teacher Management Modals
  TEACHER_ADD_NEW: "TEACHER_ADD_NEW",
  TEACHER_EDIT: "TEACHER_EDIT",
  TEACHER_DELETE_CONFIRMATION: "TEACHER_DELETE_CONFIRMATION",
  TEACHER_ASSIGN_COURSE: "TEACHER_ASSIGN_COURSE",
  TEACHER_ASSIGN_CLASS: "TEACHER_ASSIGN_CLASS",
  TEACHER_VIEW_DETAILS: "TEACHER_VIEW_DETAILS",
  
  // Student Management Modals
  STUDENT_ADD_NEW: "STUDENT_ADD_NEW",
  STUDENT_EDIT: "STUDENT_EDIT",
  STUDENT_DELETE_CONFIRMATION: "STUDENT_DELETE_CONFIRMATION",
  STUDENT_ASSIGN_CLASS: "STUDENT_ASSIGN_CLASS",
  UPDATE_STUDENT_PROGRESS: "UPDATE_STUDENT_PROGRESS",
  
  // Parent Management Modals
  PARENT_ADD_NEW: "PARENT_ADD_NEW",
  PARENT_EDIT: "PARENT_EDIT",
  PARENT_DELETE_CONFIRMATION: "PARENT_DELETE_CONFIRMATION",
  PARENT_LINK_CHILD: "PARENT_LINK_CHILD",
  
  // Announcement Management Modals
  ANNOUNCEMENT_ADD_NEW: "ANNOUNCEMENT_ADD_NEW",
  ANNOUNCEMENT_EDIT: "ANNOUNCEMENT_EDIT",
  ANNOUNCEMENT_DELETE_CONFIRMATION: "ANNOUNCEMENT_DELETE_CONFIRMATION",
  ANNOUNCEMENT_VIEW_DETAILS: "ANNOUNCEMENT_VIEW_DETAILS",
  ANNOUNCEMENT_ACKNOWLEDGE: "ANNOUNCEMENT_ACKNOWLEDGE",
  ANNOUNCEMENT_SCHEDULE: "ANNOUNCEMENT_SCHEDULE",
  ANNOUNCEMENT_ANALYTICS: "ANNOUNCEMENT_ANALYTICS",
  ANNOUNCEMENT_PREVIEW: "ANNOUNCEMENT_PREVIEW",
  ANNOUNCEMENT_PUBLISH_CONFIRMATION: "ANNOUNCEMENT_PUBLISH_CONFIRMATION",
  ANNOUNCEMENT_ARCHIVE_CONFIRMATION: "ANNOUNCEMENT_ARCHIVE_CONFIRMATION",
  
  // Assignment Management Modals
  ASSIGNMENT_ADD_NEW: "ASSIGNMENT_ADD_NEW",
  ASSIGNMENT_EDIT: "ASSIGNMENT_EDIT",
  ASSIGNMENT_DELETE_CONFIRMATION: "ASSIGNMENT_DELETE_CONFIRMATION",
  ASSIGNMENT_VIEW_DETAILS: "ASSIGNMENT_VIEW_DETAILS",
  ASSIGNMENT_VIEW_SUBMISSIONS: "ASSIGNMENT_VIEW_SUBMISSIONS",
  ASSIGNMENT_PUBLISH_CONFIRMATION: "ASSIGNMENT_PUBLISH_CONFIRMATION",
  ASSIGNMENT_CLOSE_CONFIRMATION: "ASSIGNMENT_CLOSE_CONFIRMATION",
  ASSIGNMENT_ARCHIVE_CONFIRMATION: "ASSIGNMENT_ARCHIVE_CONFIRMATION",
  ASSIGNMENT_DUPLICATE: "ASSIGNMENT_DUPLICATE",
  ASSIGNMENT_BULK_ACTIONS: "ASSIGNMENT_BULK_ACTIONS",
  
  // Submission Management Modals
  SUBMISSION_CREATE: "SUBMISSION_CREATE",
  SUBMISSION_EDIT: "SUBMISSION_EDIT",
  SUBMISSION_VIEW_DETAILS: "SUBMISSION_VIEW_DETAILS",
  SUBMISSION_GRADE: "SUBMISSION_GRADE",
  SUBMISSION_FEEDBACK: "SUBMISSION_FEEDBACK",
  SUBMISSION_DELETE_CONFIRMATION: "SUBMISSION_DELETE_CONFIRMATION",
  SUBMISSION_RETURN_CONFIRMATION: "SUBMISSION_RETURN_CONFIRMATION",
  SUBMISSION_UPLOAD_FILE: "SUBMISSION_UPLOAD_FILE",
  SUBMISSION_DOWNLOAD_FILE: "SUBMISSION_DOWNLOAD_FILE",
  SUBMISSION_PLAGIARISM_REPORT: "SUBMISSION_PLAGIARISM_REPORT",
  SUBMISSION_BULK_GRADE: "SUBMISSION_BULK_GRADE",
  SUBMISSION_REVIEW: "SUBMISSION_REVIEW",
  
  // Grade Category Management Modals
  GRADE_CATEGORY_ADD_NEW: "GRADE_CATEGORY_ADD_NEW",
  GRADE_CATEGORY_EDIT: "GRADE_CATEGORY_EDIT",
  GRADE_CATEGORY_DELETE_CONFIRMATION: "GRADE_CATEGORY_DELETE_CONFIRMATION",
  
  // Quiz Management Modals
  QUIZ_ADD_NEW: "QUIZ_ADD_NEW",
  QUIZ_EDIT: "QUIZ_EDIT",
  QUIZ_DELETE_CONFIRMATION: "QUIZ_DELETE_CONFIRMATION",
  QUIZ_VIEW_DETAILS: "QUIZ_VIEW_DETAILS",
  QUIZ_SETTINGS: "QUIZ_SETTINGS",
  QUIZ_PUBLISH_CONFIRMATION: "QUIZ_PUBLISH_CONFIRMATION",
  QUIZ_ARCHIVE_CONFIRMATION: "QUIZ_ARCHIVE_CONFIRMATION",
  QUIZ_DUPLICATE: "QUIZ_DUPLICATE",
  QUIZ_PREVIEW: "QUIZ_PREVIEW",
  QUIZ_RESULTS_VIEW: "QUIZ_RESULTS_VIEW",
  QUIZ_ANALYTICS: "QUIZ_ANALYTICS",
  
  // Question Management Modals
  QUESTION_ADD_NEW: "QUESTION_ADD_NEW",
  QUESTION_EDIT: "QUESTION_EDIT",
  QUESTION_DELETE_CONFIRMATION: "QUESTION_DELETE_CONFIRMATION",
  QUESTION_PREVIEW: "QUESTION_PREVIEW",
  QUESTION_BULK_IMPORT: "QUESTION_BULK_IMPORT",
  QUESTION_BANK_SELECT: "QUESTION_BANK_SELECT",
  
  // Quiz Submission Modals
  QUIZ_SUBMISSION_VIEW: "QUIZ_SUBMISSION_VIEW",
  QUIZ_SUBMISSION_GRADE: "QUIZ_SUBMISSION_GRADE",
  QUIZ_SUBMISSION_FEEDBACK: "QUIZ_SUBMISSION_FEEDBACK",
  QUIZ_SUBMISSION_DELETE_CONFIRMATION: "QUIZ_SUBMISSION_DELETE_CONFIRMATION",
  QUIZ_SUBMIT_CONFIRMATION: "QUIZ_SUBMIT_CONFIRMATION",
  QUIZ_TIME_WARNING: "QUIZ_TIME_WARNING",
  QUIZ_AUTO_SUBMIT: "QUIZ_AUTO_SUBMIT",
  
  // System Management Modals
  SYSTEM_RULE_ADD_NEW: "SYSTEM_RULE_ADD_NEW",
  SYSTEM_RULE_EDIT: "SYSTEM_RULE_EDIT",
  SYSTEM_RULE_DELETE_CONFIRMATION: "SYSTEM_RULE_DELETE_CONFIRMATION",
  
  // General Confirmation Modal
  CONFIRMATION: "CONFIRMATION",
  
  // Default Empty Modal
  DEFAULT: "DEFAULT"
};

export const RIGHT_DRAWER_TYPES = {
  // Admin Related Right Drawers
  AUDIT_LOGS: "AUDIT_LOGS",
  SYSTEM_NOTIFICATIONS: "SYSTEM_NOTIFICATIONS",
  USER_ACTIVITY: "USER_ACTIVITY",
  SYSTEM_HEALTH: "SYSTEM_HEALTH",
  NATIONAL_REPORTS: "NATIONAL_REPORTS",
  
  // Monitoring Related Right Drawers
  SYSTEM_MONITORING: "SYSTEM_MONITORING",
  USAGE_ANALYTICS: "USAGE_ANALYTICS",
  PERFORMANCE_METRICS: "PERFORMANCE_METRICS",
  REGIONAL_MONITORING: "REGIONAL_MONITORING",
  SCHOOL_MONITORING: "SCHOOL_MONITORING",
  
  // Assignment and Submission Related Right Drawers
  ASSIGNMENT_ANALYTICS: "ASSIGNMENT_ANALYTICS",
  SUBMISSION_ANALYTICS: "SUBMISSION_ANALYTICS",
  GRADING_QUEUE: "GRADING_QUEUE",
  LATE_SUBMISSIONS: "LATE_SUBMISSIONS",
  PLAGIARISM_ALERTS: "PLAGIARISM_ALERTS",
  
  // General Right Drawers
  NOTIFICATIONS: "NOTIFICATIONS",
  SETTINGS: "SETTINGS",
  HELP: "HELP"
}; 