export const MODAL_BODY_TYPES = {
  // User Management Modals
  USER_ADD_NEW: "USER_ADD_NEW",
  USER_EDIT: "USER_EDIT",
  USER_DELETE_CONFIRMATION: "USER_DELETE_CONFIRMATION",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",
  
  // School Management Modals
  SCHOOL_ADD_NEW: "SCHOOL_ADD_NEW",
  SCHOOL_EDIT: "SCHOOL_EDIT",
  SCHOOL_DELETE_CONFIRMATION: "SCHOOL_DELETE_CONFIRMATION",
  SCHOOL_ASSIGN_ADMIN: "SCHOOL_ASSIGN_ADMIN",
  
  // Region Management Modals
  REGION_ADD_NEW: "REGION_ADD_NEW",
  REGION_EDIT: "REGION_EDIT",
  REGION_DELETE_CONFIRMATION: "REGION_DELETE_CONFIRMATION",
  
  // Role Management Modals
  ROLE_ADD_NEW: "ROLE_ADD_NEW",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE_CONFIRMATION: "ROLE_DELETE_CONFIRMATION",
  ROLE_ASSIGN_PERMISSIONS: "ROLE_ASSIGN_PERMISSIONS",
  
  // Course Management Modals
  COURSE_ADD_NEW: "COURSE_ADD_NEW",
  COURSE_EDIT: "COURSE_EDIT",
  COURSE_DELETE_CONFIRMATION: "COURSE_DELETE_CONFIRMATION",
  COURSE_ASSIGN_TEACHER: "COURSE_ASSIGN_TEACHER",
  COURSE_VIEW: "COURSE_VIEW",
  
  // Subject Management Modals
  SUBJECT_ADD_NEW: "SUBJECT_ADD_NEW",
  SUBJECT_EDIT: "SUBJECT_EDIT",
  SUBJECT_DELETE_CONFIRMATION: "SUBJECT_DELETE_CONFIRMATION",
  SUBJECT_ASSIGN_TEACHER: "SUBJECT_ASSIGN_TEACHER",
  
  // Curriculum Management Modals
  CURRICULUM_ADD_NEW: "CURRICULUM_ADD_NEW",
  CURRICULUM_EDIT: "CURRICULUM_EDIT",
  CURRICULUM_DELETE_CONFIRMATION: "CURRICULUM_DELETE_CONFIRMATION",
  CURRICULUM_VIEW: "CURRICULUM_VIEW",
  CURRICULUM_APPROVE: "CURRICULUM_APPROVE",
  CURRICULUM_DUPLICATE: "CURRICULUM_DUPLICATE",
  CURRICULUM_ARCHIVE: "CURRICULUM_ARCHIVE",
  CURRICULUM_ACTIVATE: "CURRICULUM_ACTIVATE",
  CURRICULUM_SUSPEND: "CURRICULUM_SUSPEND",
  
  // Content Management Modals
  CONTENT_ADD_NEW: "CONTENT_ADD_NEW",
  CONTENT_EDIT: "CONTENT_EDIT",
  CONTENT_DELETE_CONFIRMATION: "CONTENT_DELETE_CONFIRMATION",
  CONTENT_VIEW: "CONTENT_VIEW",
  CONTENT_SHARE: "CONTENT_SHARE",
  CONTENT_VERSION: "CONTENT_VERSION",
  CONTENT_PREVIEW: "CONTENT_PREVIEW",
  CONTENT_UPLOAD: "CONTENT_UPLOAD",
  
  // Class Management Modals
  CLASS_ADD_NEW: "CLASS_ADD_NEW",
  CLASS_EDIT: "CLASS_EDIT",
  CLASS_DELETE_CONFIRMATION: "CLASS_DELETE_CONFIRMATION",
  CLASS_VIEW: "CLASS_VIEW",
  CLASS_ASSIGN_STUDENT: "CLASS_ASSIGN_STUDENT",
  ATTENDANCE_TAKE: "ATTENDANCE_TAKE",
  REPORT_GENERATE: "REPORT_GENERATE",
  CALENDAR_VIEW: "CALENDAR_VIEW",
  
  // Attendance Management Modals
  ATTENDANCE_MARK: "ATTENDANCE_MARK",
  ATTENDANCE_EDIT: "ATTENDANCE_EDIT",
  ATTENDANCE_REPORT: "ATTENDANCE_REPORT",
  ATTENDANCE_BULK_UPDATE: "ATTENDANCE_BULK_UPDATE",
  
  // Student Management Modals
  STUDENT_ADD_NEW: "STUDENT_ADD_NEW",
  STUDENT_EDIT: "STUDENT_EDIT",
  STUDENT_DELETE_CONFIRMATION: "STUDENT_DELETE_CONFIRMATION",
  STUDENT_ASSIGN_CLASS: "STUDENT_ASSIGN_CLASS",
  STUDENT_VIEW_PROFILE: "STUDENT_VIEW_PROFILE",
  STUDENT_PERFORMANCE_VIEW: "STUDENT_PERFORMANCE_VIEW",
  STUDENT_BULK_IMPORT: "STUDENT_BULK_IMPORT",
  STUDENT_BULK_EXPORT: "STUDENT_BULK_EXPORT",
  
  // Parent Management Modals
  PARENT_ADD_NEW: "PARENT_ADD_NEW",
  PARENT_EDIT: "PARENT_EDIT",
  PARENT_DELETE_CONFIRMATION: "PARENT_DELETE_CONFIRMATION",
  PARENT_ASSIGN_CHILD: "PARENT_ASSIGN_CHILD",
  PARENT_VIEW_PROFILE: "PARENT_VIEW_PROFILE",
  
  // Teacher Management Modals
  TEACHER_ADD_NEW: "TEACHER_ADD_NEW",
  TEACHER_EDIT: "TEACHER_EDIT",
  TEACHER_DELETE_CONFIRMATION: "TEACHER_DELETE_CONFIRMATION",
  TEACHER_ASSIGN_SUBJECT: "TEACHER_ASSIGN_SUBJECT",
  TEACHER_ASSIGN_CLASS: "TEACHER_ASSIGN_CLASS",
  TEACHER_VIEW_PROFILE: "TEACHER_VIEW_PROFILE",
  
  // Assignment Management Modals
  ASSIGNMENT_ADD_NEW: "ASSIGNMENT_ADD_NEW",
  ASSIGNMENT_EDIT: "ASSIGNMENT_EDIT",
  ASSIGNMENT_DELETE_CONFIRMATION: "ASSIGNMENT_DELETE_CONFIRMATION",
  ASSIGNMENT_VIEW: "ASSIGNMENT_VIEW",
  ASSIGNMENT_GRADE: "ASSIGNMENT_GRADE",
  ASSIGNMENT_BULK_GRADE: "ASSIGNMENT_BULK_GRADE",
  
  // Submission Management Modals
  SUBMISSION_VIEW: "SUBMISSION_VIEW",
  SUBMISSION_GRADE: "SUBMISSION_GRADE",
  SUBMISSION_FEEDBACK: "SUBMISSION_FEEDBACK",
  SUBMISSION_PLAGIARISM_CHECK: "SUBMISSION_PLAGIARISM_CHECK",
  
  // Grade Management Modals
  GRADE_ADD_NEW: "GRADE_ADD_NEW",
  GRADE_EDIT: "GRADE_EDIT",
  GRADE_DELETE_CONFIRMATION: "GRADE_DELETE_CONFIRMATION",
  GRADE_BULK_UPDATE: "GRADE_BULK_UPDATE",
  GRADE_EXPORT: "GRADE_EXPORT",
  
  // Quiz Management Modals
  QUIZ_ADD_NEW: "QUIZ_ADD_NEW",
  QUIZ_EDIT: "QUIZ_EDIT",
  QUIZ_DELETE_CONFIRMATION: "QUIZ_DELETE_CONFIRMATION",
  QUIZ_VIEW: "QUIZ_VIEW",
  QUIZ_TAKE: "QUIZ_TAKE",
  QUIZ_RESULTS: "QUIZ_RESULTS",
  QUIZ_ANALYTICS: "QUIZ_ANALYTICS",
  
  // Question Management Modals
  QUESTION_ADD_NEW: "QUESTION_ADD_NEW",
  QUESTION_EDIT: "QUESTION_EDIT",
  QUESTION_DELETE_CONFIRMATION: "QUESTION_DELETE_CONFIRMATION",
  QUESTION_BULK_IMPORT: "QUESTION_BULK_IMPORT",
  
  // Announcement Management Modals
  ANNOUNCEMENT_ADD_NEW: "ANNOUNCEMENT_ADD_NEW",
  ANNOUNCEMENT_EDIT: "ANNOUNCEMENT_EDIT",
  ANNOUNCEMENT_DELETE_CONFIRMATION: "ANNOUNCEMENT_DELETE_CONFIRMATION",
  ANNOUNCEMENT_VIEW: "ANNOUNCEMENT_VIEW",
  ANNOUNCEMENT_SCHEDULE: "ANNOUNCEMENT_SCHEDULE",
  
  // Calendar Event Management Modals
  CALENDAR_EVENT_ADD_NEW: "CALENDAR_EVENT_ADD_NEW",
  CALENDAR_EVENT_EDIT: "CALENDAR_EVENT_EDIT",
  CALENDAR_EVENT_DELETE_CONFIRMATION: "CALENDAR_EVENT_DELETE_CONFIRMATION",
  CALENDAR_EVENT_VIEW: "CALENDAR_EVENT_VIEW",
  CALENDAR_EVENT_APPROVE: "CALENDAR_EVENT_APPROVE",
  CALENDAR_EVENT_REJECT: "CALENDAR_EVENT_REJECT",
  CALENDAR_EVENT_CANCEL: "CALENDAR_EVENT_CANCEL",
  CALENDAR_EVENT_POSTPONE: "CALENDAR_EVENT_POSTPONE",
  CALENDAR_EVENT_RESCHEDULE: "CALENDAR_EVENT_RESCHEDULE",
  CALENDAR_EVENT_ADD_ATTENDEE: "CALENDAR_EVENT_ADD_ATTENDEE",
  CALENDAR_EVENT_REMOVE_ATTENDEE: "CALENDAR_EVENT_REMOVE_ATTENDEE",
  CALENDAR_EVENT_ADD_ORGANIZER: "CALENDAR_EVENT_ADD_ORGANIZER",
  CALENDAR_EVENT_REMOVE_ORGANIZER: "CALENDAR_EVENT_REMOVE_ORGANIZER",
  CALENDAR_EVENT_CONFLICT_RESOLUTION: "CALENDAR_EVENT_CONFLICT_RESOLUTION",
  CALENDAR_EVENT_BULK_CREATE: "CALENDAR_EVENT_BULK_CREATE",
  CALENDAR_EVENT_BULK_DELETE: "CALENDAR_EVENT_BULK_DELETE",
  CALENDAR_EVENT_EXPORT: "CALENDAR_EVENT_EXPORT",
  
  // General Modals
  CONFIRMATION: "CONFIRMATION",
  LOADING: "LOADING",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  INFO: "INFO",
  WARNING: "WARNING"
};

export const RIGHT_DRAWER_TYPES = {
  // User Related Right Drawers
  USER_PROFILE: "USER_PROFILE",
  USER_SETTINGS: "USER_SETTINGS",
  USER_ACTIVITY: "USER_ACTIVITY",
  USER_PERMISSIONS: "USER_PERMISSIONS",
  
  // School Related Right Drawers
  SCHOOL_DETAILS: "SCHOOL_DETAILS",
  SCHOOL_STATISTICS: "SCHOOL_STATISTICS",
  SCHOOL_RESOURCES: "SCHOOL_RESOURCES",
  SCHOOL_CALENDAR: "SCHOOL_CALENDAR",
  
  // Class Related Right Drawers
  CLASS_DETAILS: "CLASS_DETAILS",
  CLASS_ROSTER: "CLASS_ROSTER",
  CLASS_SCHEDULE: "CLASS_SCHEDULE",
  CLASS_PERFORMANCE: "CLASS_PERFORMANCE",
  
  // Student Related Right Drawers
  STUDENT_PROFILE: "STUDENT_PROFILE",
  STUDENT_GRADES: "STUDENT_GRADES",
  STUDENT_ATTENDANCE: "STUDENT_ATTENDANCE",
  STUDENT_ASSIGNMENTS: "STUDENT_ASSIGNMENTS",
  STUDENT_PROGRESS: "STUDENT_PROGRESS",
  
  // Teacher Related Right Drawers
  TEACHER_PROFILE: "TEACHER_PROFILE",
  TEACHER_CLASSES: "TEACHER_CLASSES",
  TEACHER_SUBJECTS: "TEACHER_SUBJECTS",
  TEACHER_SCHEDULE: "TEACHER_SCHEDULE",
  
  // Course Related Right Drawers
  COURSE_DETAILS: "COURSE_DETAILS",
  COURSE_CURRICULUM: "COURSE_CURRICULUM",
  COURSE_RESOURCES: "COURSE_RESOURCES",
  COURSE_ANALYTICS: "COURSE_ANALYTICS",
  
  // Assignment Related Right Drawers
  ASSIGNMENT_DETAILS: "ASSIGNMENT_DETAILS",
  ASSIGNMENT_SUBMISSIONS: "ASSIGNMENT_SUBMISSIONS",
  ASSIGNMENT_GRADING: "ASSIGNMENT_GRADING",
  ASSIGNMENT_ANALYTICS: "ASSIGNMENT_ANALYTICS",
  SUBMISSION_ANALYTICS: "SUBMISSION_ANALYTICS",
  GRADING_QUEUE: "GRADING_QUEUE",
  LATE_SUBMISSIONS: "LATE_SUBMISSIONS",
  PLAGIARISM_ALERTS: "PLAGIARISM_ALERTS",
  
  // Grade Related Right Drawers
  GRADE_BREAKDOWN: "GRADE_BREAKDOWN",
  GRADE_HISTORY: "GRADE_HISTORY",
  GRADE_ANALYTICS: "GRADE_ANALYTICS",
  GRADE_TRENDS: "GRADE_TRENDS",
  
  // Reports Related Right Drawers
  ATTENDANCE_REPORTS: "ATTENDANCE_REPORTS",
  PERFORMANCE_REPORTS: "PERFORMANCE_REPORTS",
  ACADEMIC_REPORTS: "ACADEMIC_REPORTS",
  FINANCIAL_REPORTS: "FINANCIAL_REPORTS",
  REGIONAL_REPORTS: "REGIONAL_REPORTS",
  NATIONAL_REPORTS: "NATIONAL_REPORTS",
  
  // Monitoring Related Right Drawers
  SYSTEM_MONITORING: "SYSTEM_MONITORING",
  USAGE_ANALYTICS: "USAGE_ANALYTICS",
  PERFORMANCE_METRICS: "PERFORMANCE_METRICS",
  REGIONAL_MONITORING: "REGIONAL_MONITORING",
  SCHOOL_MONITORING: "SCHOOL_MONITORING",
  
  // General Right Drawers
  NOTIFICATIONS: "NOTIFICATIONS",
  SETTINGS: "SETTINGS",
  HELP: "HELP"
}; 